# Generated by Django 5.1.7 on 2025-04-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_massage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='message',
            name='fullname',
            field=models.CharField(blank=True, max_length=60, verbose_name='full name'),
        ),
    ]
